-- ==================================================
-- * Campfire Project | Framework/Client/Main.lua
-- *
-- * Info:
-- * Campfire Project Framework Client Entry
-- *
-- * Framework Powered By UniX Architecture
-- *
-- * 2025 © RoidMC Studios | Powered by UniX SDK
-- ==================================================