-- ==================================================
-- * Campfire Project | Config/UI.lua
-- *
-- * Info:
-- * Campfire Project UI Config
-- *
-- * Description:
-- * T : Text文本
-- * Grp : Group编组
-- * Btn : Button按钮
-- * Img : Image图片
-- * Tmp : Template模板
-- * Tgl : Toggle开关
-- * Lbl : Label标签
-- * Clr : Color颜色
-- * Fc: Function功能控件
-- *
-- * 2025 © RoidMC Studios | Powered by UniX SDK
-- ==================================================

local UIConf = {}

return UIConf