-- ==================================================
-- * Campfire Project | Framework/Common/Main.lua
-- *
-- * Info:
-- * Campfire Project Framework C/S Common Entry
-- *
-- * Framework Powered By UniX Architecture
-- *
-- * 2025 © RoidMC Studios | Powered by UniX SDK
-- ==================================================